[tool.poetry]
name = "streamlit"
version = "0.1.0"
description = ""
authors = ["Nikos Kallergis <nikos.kallergis@networktocode.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
